[package]
name = "sylver-langs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.9"
tree-sitter-python = "0.20.2"

[build-dependencies]
cc = "*"
